spring:
  profiles:
    active: local

# "---"でプロファイルを区切る
# プロファイル名はspring.profilesに書く
---
spring:
  profiles: local
  profiles.include:
    - common
    - local
---
spring:
  profiles: release
  profiles.include:
    - common
    - release